### ISSUE TITLE
Publish hex.pm package?

### ISSUE THREAD

**Issue by scrogson** [esl/exml#15]
Hey folks, I'm curious if you would be interested in publishing this library to https://hex.pm ?

**Comment by michalwski** [comment]
Hi, I think we would be interested in publishing this library but I think you should ask @paulgray first, as he's the author of the exml lib.

**Comment by scrogson** [comment]
Are you guys contributing back to the main repo? They seem pretty far out of sync.

**Comment by michalwski** [comment]
We are planning to contribute back. The reason why we didn't do it yet is the fact that we still support Erlang R15B03 and the main repo has some features which require at least R16. We are going to end supporting R15B03 and this will allow as to sync with the main repo. I'm not sure if our changes will be accepted though, but hopefully they will :)

**Comment by michalwski** [comment]
I've just checked hex.pm and noticed that there is package `exml` already: https://hex.pm/packages/exml. How this and the the other `exml` will work in hex?

**Comment by scrogson** [comment]
You will have to modify your package name. Kind of a bummer, but necessary in this case.
