### ISSUE TITLE
Extend exml_query:path/2

### ISSUE THREAD

**Issue by arcusfelis** [esl/exml#27]
We have `{element, <<"name">>}` selector, but it's often not enough.
Let's do more selectors:
- `{element_with_ns, <<"query">>, <<"urn:xmpp:mam:0">>}`
- `{element_with_attr, <<"field">>, <<"var">>, <<"title">>}`
- `{element_fun, fun(Elem) -> Matched :: boolean() end}`
- `{element_match, #xmlel{name = <<"user">>, attrs = [{<<"jid">>, <<"alice@localhost">>}]}`

element_with_ns matches `<query xmlns="urn:xmpp:mam:0"/>` but not `<query xmlns="urn:xmpp:mam:2"/>`.
element_with_attr matches `<field var="title"/>` but not `<field var="description"/>`.
element_math matches `<user jid="alice@localhost" nick="Alice"><active/></user>`.

**Comment by michalwski** [comment]
For the `element_with_attr` selector I suggest the following syntax:
`{element_with_attr, <<"field">>, {<<"var">>, <<"title">>}}`
since attributes are already represented as a tuple.

**Comment by NelsonVides** [comment]
My understanding is that for this request the first two selectors were already implemented. The next two aren't but they seem to me to be a bit over-engineered. Maybe there's a good use-case, if so please open a new issue explaining them.
