### ISSUE TITLE
Whitespace Parsing

### ISSUE THREAD

**Issue by GalaxyGorilla** [esl/exml#37]
Currently whitespaces are not honored by exml:

```
# exml:parse(<<"<body> </body>">>).
{ok,{xmlel,<<"body">>,[],[]}}
```

The whitespace is not parsed as content of the XML tag. My first guess is that the `parse_non_destructive` has to be used in the rapidxml parser, but that did not work out so far :(.

**Comment by fenek** [comment]
It is a necessary behaviour, because any white spaces between tags may be a result of pretty printing. If you'd like to include them as a content of a tag, please add them explicitly as CDATA:
```erlang
exml:parse(<<"<body><![CDATA[ ]]></body>">>).
{ok,{xmlel,<<"body">>,[],[{xmlcdata,<<" ">>}]}}
```

**Comment by GalaxyGorilla** [comment]
Ah cool, thanks for the explanation ;)
